spring:
  application:
    name: eureka.server
  cloud:
    config:
      uri: http://localhost:4444

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
