spring:
  application:
    name: servicio.cesta
  datasource:
    url: jdbc:mysql://localhost:3306/carritomicro?useSSL=false&serverTimezone=UTC
    username: root
    password: vertrigo
  jpa:
    generate-ddl: true
    
server:
  port: 3333

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka